feat: add sway powermenu

diff --git a/ui/i3/scripts/powermenu b/ui/i3/scripts/powermenu
--- a/ui/i3/scripts/powermenu
+++ b/ui/i3/scripts/powermenu
@@ -1,186 +1,264 @@
 #!/usr/bin/env bash
+
+# This script defines just a mode for rofi instead of being a self-contained
+# executable that launches rofi by itself. This makes it more flexible than
+# running rofi inside this script as now the user can call rofi as one pleases.
+# For instance:
 #
-# Use rofi/zenity to change system runstate thanks to systemd.
+#   rofi -show powermenu -modi powermenu:./rofi-power-menu
 #
-# Note: this currently relies on associative array support in the shell.
-#
-# Inspired from i3pystatus wiki:
-# https://github.com/enkore/i3pystatus/wiki/Shutdown-Menu
-#
-# Copyright 2015 Benjamin Chrétien <chretien at lirmm dot fr>
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
+# See README.md for more information.
 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
+set -e
+set -u
 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# All supported choices
+all=(shutdown reboot suspend hibernate logout lockscreen)
 
-# modified to work with latest rofi update by joekamprad <joekamprad@endeavouros.com>
+# By default, show all (i.e., just copy the array)
+show=("${all[@]}")
 
-#######################################################################
-#                            BEGIN CONFIG                             #
-#######################################################################
+declare -A texts
+texts[lockscreen]="lock screen"
+texts[switchuser]="switch user"
+texts[logout]="log out"
+texts[suspend]="suspend"
+texts[hibernate]="hibernate"
+texts[reboot]="reboot"
+texts[shutdown]="shut down"
 
-# Use a custom lock script
-#LOCKSCRIPT="i3lock-extra -m pixelize"
+declare -A icons
+icons[lockscreen]="\Uf033e"
+icons[switchuser]="\Uf0019"
+icons[logout]="\Uf0343"
+icons[suspend]="\Uf04b2"
+icons[hibernate]="\Uf02ca"
+icons[reboot]="\Uf0709"
+icons[shutdown]="\Uf0425"
+icons[cancel]="\Uf0156"
 
-# Colors: FG (foreground), BG (background), HL (highlighted)
-FG_COLOR="#bbbbbb"
-BG_COLOR="#111111"
-HLFG_COLOR="#111111"
-HLBG_COLOR="#bbbbbb"
-BORDER_COLOR="#222222"
+declare -A actions
+actions[lockscreen]="loginctl lock-session ${XDG_SESSION_ID-}"
+#actions[switchuser]="???"
+actions[logout]="loginctl terminate-session ${XDG_SESSION_ID-}"
+actions[suspend]="systemctl suspend"
+actions[hibernate]="systemctl hibernate"
+actions[reboot]="systemctl reboot"
+actions[shutdown]="systemctl poweroff"
 
-# Options not related to colors (most rofi options do not work anymore)
-# ROFI_OPTIONS=(-theme ~/.config/rofi/powermenu.rasi)
-# Zenity options
-ZENITY_TITLE="Power Menu"
-ZENITY_TEXT="Action:"
-ZENITY_OPTIONS=(--column= --hide-header)
+# By default, ask for confirmation for actions that are irreversible
+confirmations=(reboot shutdown logout)
 
-#######################################################################
-#                             END CONFIG                              #
-#######################################################################
+# By default, no dry run
+dryrun=false
+showsymbols=true
+showtext=true
 
-# Whether to ask for user's confirmation
-enable_confirmation=false
-
-# Preferred launcher if both are available
-preferred_launcher="rofi"
-
-usage="$(basename "$0") [-h] [-c] [-p name] -- display a menu for shutdown, reboot, lock etc.
-
-where:
-    -h  show this help text
-    -c  ask for user confirmation
-    -p  preferred launcher (rofi or zenity)
-
-This script depends on:
-  - systemd,
-  - i3,
-  - rofi or zenity."
-
-# Check whether the user-defined launcher is valid
-launcher_list=(rofi zenity)
-function check_launcher() {
-  if [[ ! "${launcher_list[@]}" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
-    echo "Supported launchers: ${launcher_list[*]}"
-    exit 1
-  else
-    # Get array with unique elements and preferred launcher first
-    # Note: uniq expects a sorted list, so we cannot use it
-    i=1
-    launcher_list=($(for l in "$1" "${launcher_list[@]}"; do printf "%i %s\n" "$i" "$l"; let i+=1; done \
-      | sort -uk2 | sort -nk1 | cut -d' ' -f2- | tr '\n' ' '))
-  fi
+function check_valid {
+  option="$1"
+  shift 1
+  for entry in "${@}"; do
+    if [ -z "${actions[$entry]+x}" ]; then
+      echo "Invalid choice in $1: $entry" >&2
+      exit 1
+    fi
+  done
 }
 
-# Parse CLI arguments
-while getopts "hcp:" option; do
-  case "${option}" in
-    h) echo "${usage}"
-       exit 0
-       ;;
-    c) enable_confirmation=true
-       ;;
-    p) preferred_launcher="${OPTARG}"
-       check_launcher "${preferred_launcher}"
-       ;;
-    *) exit 1
-       ;;
+# Parse command-line options
+parsed=$(getopt --options=h --longoptions=help,dry-run,confirm:,choices:,choose:,symbols,no-symbols,text,no-text,symbols-font: --name "$0" -- "$@")
+if [ $? -ne 0 ]; then
+  echo 'Terminating...' >&2
+  exit 1
+fi
+eval set -- "$parsed"
+unset parsed
+while true; do
+  case "$1" in
+  "-h" | "--help")
+    echo "rofi-power-menu - a power menu mode for Rofi"
+    echo
+    echo "Usage: rofi-power-menu [--choices CHOICES] [--confirm CHOICES]"
+    echo "                       [--choose CHOICE] [--dry-run] [--symbols|--no-symbols]"
+    echo
+    echo "Use with Rofi in script mode. For instance, to ask for shutdown or reboot:"
+    echo
+    echo "  rofi -show menu -modi \"menu:rofi-power-menu --choices=shutdown/reboot\""
+    echo
+    echo "Available options:"
+    echo "  --dry-run            Don't perform the selected action but print it to stderr."
+    echo "  --choices CHOICES    Show only the selected choices in the given order. Use /"
+    echo "                       as the separator. Available choices are lockscreen,"
+    echo "                       logout,suspend, hibernate, reboot and shutdown. By"
+    echo "                       default, all available choices are shown."
+    echo "  --confirm CHOICES    Require confirmation for the gives choices only. Use / as"
+    echo "                       the separator. Available choices are lockscreen, logout,"
+    echo "                       suspend, hibernate, reboot and shutdown. By default, only"
+    echo "                       irreversible actions logout, reboot and shutdown require"
+    echo "                       confirmation."
+    echo "  --choose CHOICE      Preselect the given choice and only ask for a"
+    echo "                       confirmation (if confirmation is set to be requested). It"
+    echo "                       is strongly recommended to combine this option with"
+    echo "                       --confirm=CHOICE if the choice wouldn't require"
+    echo "                       confirmation by default. Available choices are"
+    echo "                       lockscreen, logout, suspend, hibernate, reboot and"
+    echo "                       shutdown."
+    echo "  --[no-]symbols       Show Unicode symbols or not. Requires a font with support"
+    echo "                       for the symbols. Use, for instance, fonts from the"
+    echo "                       Nerdfonts collection. By default, they are shown"
+    echo "  --[no-]text          Show text description or not."
+    echo "  --symbols-font FONT  Use the given font for symbols. By default, the symbols"
+    echo "                       use the same font as the text. That font is configured"
+    echo "                       with rofi."
+    echo "  -h,--help            Show this help text."
+    exit 0
+    ;;
+  "--dry-run")
+    dryrun=true
+    shift 1
+    ;;
+  "--confirm")
+    IFS='/' read -ra confirmations <<<"$2"
+    check_valid "$1" "${confirmations[@]}"
+    shift 2
+    ;;
+  "--choices")
+    IFS='/' read -ra show <<<"$2"
+    check_valid "$1" "${show[@]}"
+    shift 2
+    ;;
+  "--choose")
+    # Check that the choice is valid
+    check_valid "$1" "$2"
+    selectionID="$2"
+    shift 2
+    ;;
+  "--symbols")
+    showsymbols=true
+    shift 1
+    ;;
+  "--no-symbols")
+    showsymbols=false
+    shift 1
+    ;;
+  "--text")
+    showtext=true
+    shift 1
+    ;;
+  "--no-text")
+    showtext=false
+    shift 1
+    ;;
+  "--symbols-font")
+    symbols_font="$2"
+    shift 2
+    ;;
+  "--")
+    shift
+    break
+    ;;
+  *)
+    echo "Internal error" >&2
+    exit 1
+    ;;
   esac
 done
 
-# Check whether a command exists
-function command_exists() {
-  command -v "$1" &> /dev/null 2>&1
-}
-
-# systemctl required
-if ! command_exists systemctl ; then
+if [ "$showsymbols" = "false" -a "$showtext" = "false" ]; then
+  echo "Invalid options: cannot have --no-symbols and --no-text enabled at the same time." >&2
   exit 1
 fi
 
-# menu defined as an associative array
-typeset -A menu
+# Define the messages after parsing the CLI options so that it is possible to
+# configure them in the future.
 
-# Menu with keys/commands
-
-menu=(
-  [ Shutdown]="systemctl poweroff"
-  [ Reboot]="systemctl reboot"
-  [ Suspend]="systemctl suspend"
-  [ Hibernate]="systemctl hibernate"
- # [ Lock]="~/.config/i3/scripts/blur-lock"
-  [ Logout]="i3-msg exit"
-  [ Cancel]=""
-)
-
-menu_nrows=${#menu[@]}
-
-# Menu entries that may trigger a confirmation message
-menu_confirm="Shutdown Reboot Hibernate Suspend Halt Logout"
-
-launcher_exe=""
-launcher_options=""
-rofi_colors=""
-
-function prepare_launcher() {
-  if [[ "$1" == "rofi" ]]; then
-    rofi_colors=(-bc "${BORDER_COLOR}" -bg "${BG_COLOR}" -fg "${FG_COLOR}" \
-        -hlfg "${HLFG_COLOR}" -hlbg "${HLBG_COLOR}")
-    launcher_exe="rofi"
-    launcher_options=(-dmenu -i -lines "${menu_nrows}" -p "${ROFI_TEXT}" \
-        "${rofi_colors}" "${ROFI_OPTIONS[@]}")
-  elif [[ "$1" == "zenity" ]]; then
-    launcher_exe="zenity"
-    launcher_options=(--list --title="${ZENITY_TITLE}" --text="${ZENITY_TEXT}" \
-        "${ZENITY_OPTIONS[@]}")
-  fi
-}
-
-for l in "${launcher_list[@]}"; do
-  if command_exists "${l}" ; then
-    prepare_launcher "${l}"
-    break
-  fi
-done
-
-# No launcher available
-if [[ -z "${launcher_exe}" ]]; then
-  exit 1
-fi
-
-launcher=(${launcher_exe} "${launcher_options[@]}")
-selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"
-
-function ask_confirmation() {
-  if [ "${launcher_exe}" == "rofi" ]; then
-    confirmed=$(echo -e "Yes\nNo" | rofi -dmenu -i -lines 2 -p "${selection}?" \
-      "${rofi_colors}" "${ROFI_OPTIONS[@]}")
-    [ "${confirmed}" == "Yes" ] && confirmed=0
-  elif [ "${launcher_exe}" == "zenity" ]; then
-    zenity --question --text "Are you sure you want to ${selection,,}?"
-    confirmed=$?
-  fi
-
-  if [ "${confirmed}" == 0 ]; then
-    i3-msg -q "exec --no-startup-id ${menu[${selection}]}"
-  fi
-}
-
-if [[ $? -eq 0 && ! -z ${selection} ]]; then
-  if [[ "${enable_confirmation}" = true && \
-        ${menu_confirm} =~ (^|[[:space:]])"${selection}"($|[[:space:]]) ]]; then
-    ask_confirmation
+function write_message {
+  if [ -z ${symbols_font+x} ]; then
+    icon="<span font_size=\"medium\">$1</span>"
   else
-    i3-msg -q "exec --no-startup-id ${menu[${selection}]}"
+    icon="<span font=\"${symbols_font}\" font_size=\"medium\">$1</span>"
   fi
+  text="<span font_size=\"medium\">$2</span>"
+  if [ "$showsymbols" = "true" ]; then
+    if [ "$showtext" = "true" ]; then
+      echo -n "\u200e$icon \u2068$text\u2069"
+    else
+      echo -n "\u200e$icon"
+    fi
+  else
+    echo -n "$text"
+  fi
+}
+
+function print_selection {
+  echo -e "$1" | $(
+    read -r -d '' entry
+    echo "echo $entry"
+  )
+}
+
+declare -A messages
+declare -A confirmationMessages
+for entry in "${all[@]}"; do
+  messages[$entry]=$(write_message "${icons[$entry]}" "${texts[$entry]^}")
+done
+for entry in "${all[@]}"; do
+  confirmationMessages[$entry]=$(write_message "${icons[$entry]}" "Yes, ${texts[$entry]}")
+done
+confirmationMessages[cancel]=$(write_message "${icons[cancel]}" "No, cancel")
+
+if [ $# -gt 0 ]; then
+  # If arguments given, use those as the selection
+  selection="${@}"
+else
+  # Otherwise, use the CLI passed choice if given
+  if [ -n "${selectionID+x}" ]; then
+    selection="${messages[$selectionID]}"
+  fi
+fi
+
+# Don't allow custom entries
+echo -e "\0no-custom\x1ftrue"
+# Use markup
+echo -e "\0markup-rows\x1ftrue"
+
+if [ -z "${selection+x}" ]; then
+  echo -e "\0prompt\x1fPower menu"
+  for entry in "${show[@]}"; do
+    echo -e "${messages[$entry]}\0icon\x1f${icons[$entry]}"
+  done
+else
+  for entry in "${show[@]}"; do
+    if [ "$selection" = "$(print_selection "${messages[$entry]}")" ]; then
+      # Check if the selected entry is listed in confirmation requirements
+      for confirmation in "${confirmations[@]}"; do
+        if [ "$entry" = "$confirmation" ]; then
+          # Ask for confirmation
+          echo -e "\0prompt\x1fAre you sure"
+          echo -e "${confirmationMessages[$entry]}\0icon\x1f${icons[$entry]}"
+          echo -e "${confirmationMessages[cancel]}\0icon\x1f${icons[cancel]}"
+          exit 0
+        fi
+      done
+      # If not, then no confirmation is required, so mark confirmed
+      selection=$(print_selection "${confirmationMessages[$entry]}")
+    fi
+    if [ "$selection" = "$(print_selection "${confirmationMessages[$entry]}")" ]; then
+      if [ $dryrun = true ]; then
+        # Tell what would have been done
+        echo "Selected: $entry" >&2
+      else
+        # Perform the action
+        ${actions[$entry]}
+      fi
+      exit 0
+    fi
+    if [ "$selection" = "$(print_selection "${confirmationMessages[cancel]}")" ]; then
+      # Do nothing
+      exit 0
+    fi
+  done
+  # The selection didn't match anything, so raise an error
+  echo "Invalid selection: $selection" >&2
+  exit 1
 fi
